# Generated by Django 3.1.1 on 2020-12-03 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rocky_Railway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=200)),
                ('Total_Available', models.IntegerField()),
                ('Sales', models.IntegerField()),
                ('Total_Produces', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Friends_with_God_Bible_Story',
            fields=[
                ('rocky_railway_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inventory.rocky_railway')),
            ],
            bases=('Inventory.rocky_railway',),
        ),
        migrations.CreateModel(
            name='FWN1',
            fields=[
                ('rocky_railway_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inventory.rocky_railway')),
            ],
            bases=('Inventory.rocky_railway',),
        ),
        migrations.CreateModel(
            name='FWN2',
            fields=[
                ('rocky_railway_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inventory.rocky_railway')),
            ],
            bases=('Inventory.rocky_railway',),
        ),
        migrations.CreateModel(
            name='FWN3',
            fields=[
                ('rocky_railway_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inventory.rocky_railway')),
            ],
            bases=('Inventory.rocky_railway',),
        ),
        migrations.CreateModel(
            name='Leader_Manuals',
            fields=[
                ('rocky_railway_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inventory.rocky_railway')),
            ],
            bases=('Inventory.rocky_railway',),
        ),
        migrations.CreateModel(
            name='LIFE_OF_JESUS',
            fields=[
                ('rocky_railway_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inventory.rocky_railway')),
            ],
            bases=('Inventory.rocky_railway',),
        ),
        migrations.CreateModel(
            name='Roar',
            fields=[
                ('rocky_railway_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inventory.rocky_railway')),
            ],
            bases=('Inventory.rocky_railway',),
        ),
        migrations.CreateModel(
            name='Shipwreched',
            fields=[
                ('rocky_railway_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inventory.rocky_railway')),
            ],
            bases=('Inventory.rocky_railway',),
        ),
        migrations.CreateModel(
            name='Student_Books',
            fields=[
                ('rocky_railway_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inventory.rocky_railway')),
            ],
            bases=('Inventory.rocky_railway',),
        ),
    ]
