# Generated by Django 3.1.1 on 2020-12-03 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rocky_railway',
            old_name='Total_Produces',
            new_name='Total_Produced',
        ),
    ]
