# Generated by Django 3.1.1 on 2020-12-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='Total_Available',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rocky_railway',
            name='Sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rocky_railway',
            name='Total_Available',
            field=models.IntegerField(default=0),
        ),
    ]
